name: Build and Deploy Blazor WASM to Netlify

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Zlebuh.MinTacToe.UI/Zlebuh.MinTacToe.UI.csproj

      - name: Build
        run: dotnet publish src/Zlebuh.MinTacToe.UI/Zlebuh.MinTacToe.UI.csproj -c Release -o build_output

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=build_output/wwwroot --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN